# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qmd8Uc1xENWIWzsiKk5O7JZm45eAhzI
"""

# Instalar dependências
!pip install -q transformers torch

from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import torch

# Carregar modelo
model_name = "pierreguillou/gpt2-small-portuguese"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

# Criar pipeline
chatbot = pipeline("text-generation", model=model, tokenizer=tokenizer)

# -----------------------------
# Versão 1: Respostas curtas e coerentes
# -----------------------------
def responder_curto(pergunta):
    resposta = chatbot(
        pergunta,
        max_new_tokens=50,       # respostas curtas
        do_sample=True,
        temperature=0.3,         # baixa criatividade
        top_p=0.7,               # mantém coerência
        repetition_penalty=1.5   # evita repetições
    )
    return resposta[0]['generated_text'].strip()

# -----------------------------
# Versão 2: Respostas abertas e criativas
# -----------------------------
def responder_aberto(pergunta):
    resposta = chatbot(
        pergunta,
        max_new_tokens=250,      # respostas longas
        do_sample=True,
        temperature=0.9,         # alta criatividade
        top_p=0.95,              # maior diversidade
        repetition_penalty=1.0   # menos penalização
    )
    return resposta[0]['generated_text'].strip()

# -----------------------------
# Teste com perguntas
# -----------------------------
perguntas = [
    "O que é inteligência artificial?",
    "Como funciona o aprendizado de máquina?",
    "Explique a importância da ética em IA"
]

print("🤖 Experimento LLM - Respostas curtas x criativas\n")

for pergunta in perguntas:
    print("Pergunta:", pergunta)

    # Versão curta
    resposta_curta = responder_curto(pergunta)
    print("Resposta curta/coerente:", resposta_curta)

    # Versão aberta
    resposta_aberta = responder_aberto(pergunta)
    print("Resposta aberta/criativa:", resposta_aberta)

    print("-"*80)